Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)

Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}

Config.Products = {
    ["normal"] = {
        [1] = {
            name = "tosti",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 0.60,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 0.60,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 1.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 9.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 9.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "bandage",
            price = 500.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "lighter",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "rolling_paper",
            price = 1.50,
            amount = 5000,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "redwoodcigs",
            price = 200,
            amount = 5000,
            info = {
                uses = 20
            },
            type = "item",
            slot = 11,
        },
        [14] = {
            name = "cardiaquecigs",
            price = 200,
            amount = 5000,
            info = {
                uses = 20
            },
            type = "item",
            slot = 12,
        },
        [15] = {
            name = "yukoncigs",
            price = 200,
            amount = 5000,
            info = {
                uses = 20
            },
            type = "item",
            slot = 13,
        },

    },

    ["24/7shop"] = {
        [1] = {
            name = "water_bottle",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "kurkakola",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "fanta",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "sprite",
            price = 2.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "redbull",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "espresso",
            price = 2.30,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "green_tea",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "cappuccino",
            price = 2.30,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "earl_grey_tea",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "stella",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "duvel",
            price = 3.0,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "corona",
            price = 5.0,
            amount = 5000,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "jupiler",
            price = 2.0,
            amount = 5000,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "carapils",
            price = 1.50,
            amount = 5000,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "donut",
            price = 1.50,
            amount = 5000,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "cookie",
            price = 1.20,
            amount = 5000,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "tosti",
            price = 20.00,
            amount = 5000,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "sandwich",
            price = 1.50,
            amount = 5000,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "chips",
            price = 0.90,
            amount = 5000,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "popcorn",
            price = 20.00,
            amount = 5000,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "twerks_candy",
            price = 0.60,
            amount = 5000,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "snikkel_candy",
            price = 0.60,
            amount = 5000,
            info = {},
            type = "item",
            slot = 22,
        },
    },
    ["liquor"] = {
        [1] = {
            name = "beer",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 9.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 9.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["hardware"] = {
        [1] = {
            name = "lockpick",
            price = 200.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_wrench",
            price = 250.00,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hammer",
            price = 250.00,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "repairkit",
            price = 250.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
            requiredJob = { "mechanic", "police" }
        },
        [5] = {
            name = "screwdriverset",
            price = 50.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "phone",
            price = 850.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "radio",
            price = 250.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "binoculars",
            price = 150.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "firework1",
            price = 160.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "firework2",
            price = 160.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "firework3",
            price = 160.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "firework4",
            price = 160.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "fitbit",
            price = 180.00,
            amount = 150,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "cleaningkit",
            price = 30.00,
            amount = 150,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "advancedrepairkit",
            price = 500.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
            requiredJob = { "mechanic" }
        },
    },
    ["weedshop"] = {
        [1] = {
            name = "joint",
            price = 10.00,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_poolcue",
            price = 80.00,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weed_nutrition",
            price = 100.00,
            amount = 1000,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "empty_weed_bag",
            price = 20.00,
            amount = 1000,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "rolling_paper",
            price = 1.50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 5,
        },
    },
    ["gearshop"] = {
        [1] = {
            name = "diving_gear",
            price = 2500.00,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "jerry_can",
            price = 200.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["leisureshop"] = {
        [1] = {
            name = "parachute",
            price = 200.00,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "binoculars",
            price = 150.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "diving_gear",
            price = 2500.00,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        -- [4] = {
        --     name = "smoketrailred",
        --     price = 250.00,
        --     amount = 50,
        --     info = {},
        --     type = "item",
        --     slot = 4,
        -- },
    },
    -- ["weapons"] = {
    --     [1] = {
    --         name = "weapon_knife",
    --         price = 250.00,
    --         amount = 250,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [2] = {
    --         name = "weapon_bat",
    --         price = 100.00,
    --         amount = 250,
    --         info = {},
    --         type = "item",
    --         slot = 2,
    --     },
    --     [3] = {
    --         name = "weapon_hatchet",
    --         price = 50.00,
    --         amount = 250,
    --         info = {},
    --         type = "item",
    --         slot = 3,
    --         requiredJob = { "mechanic", "police" }
    --     },
    --     [4] = {
    --         name = "weapon_pistol",
    --         price = 2500.00,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 4,
    --         requiresLicense = true
    --     },
    --     [5] = {
    --         name = "weapon_snspistol",
    --         price = 1500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 5,
    --         requiresLicense = true
    --     },
    --     [6] = {
    --         name = "weapon_vintagepistol",
    --         price = 4000,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 6,
    --         requiresLicense = true
    --     },
    --     [7] = {
    --         name = "pistol_ammo",
    --         price = 250.00,
    --         amount = 250,
    --         info = {},
    --         type = "item",
    --         slot = 7,
    --         requiresLicense = true
    --     },
    -- },
    ["coffeeplace"] = {
        [1] = {
            name = "coffee",
            price = 2.50,
            amount = 500,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "cake",
            price = 4.00,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "pie",
            price = 1.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "donut",
            price = 1.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "green_tea",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "frappuccino",
            price = 2.30,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "espresso",
            price = 2.30,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "cappuccino",
            price = 2.30,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "mint_tea",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "earl_grey_tea",
            price = 2.50,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "cookie",
            price = 1.20,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1.00,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        },
    },
    ["fishing"] = {
        [1] = {
            name = 'fishingrod',
            price = 500.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fishingbait',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
    },
    ["kfc"] = {
        [1] = {
            name = 'chickenbucket',
            price = 9.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'nuggets',
            price = 7.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'fries',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'milkshake',
            price = 2.7,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'icecream',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'cookie',
            price = 1.20,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'fanta',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
        [9] = {
            name = 'sprite',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
        [9] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
        [9] = {
            name = 'redbull',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },

    },
    ["bar"] = {
        [1] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fanta',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'sprite',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'redbull',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'corona',
            price = 5.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'stella',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'duvel',
            price = 3.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'jupiler',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'maes',
            price = 2.20,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
        [10] = {
            name = 'carapils',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 10,
        },
        [11] = {
            name = 'desperados',
            price = 5.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 11,
        },
        [12] = {
            name = 'vodka_redbull',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 12,
        },
        [13] = {
            name = 'whiskey',
            price = 9.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 13,
        },
        [14] = {
            name = 'vodka',
            price = 9.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 14,
        },
        [15] = {
            name = 'bacardi_cola',
            price = 9.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 15,
        },
        [16] = {
            name = 'martini',
            price = 7.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 16,
        },
        [17] = {
            name = 'gold_strike',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 17,
        },
        [18] = {
            name = 'boswandeling',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 18,
        },
        [19] = {
            name = 'jenever',
            price = 4.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 19,
        },
        [20] = {
            name = 'rode_wijn',
            price = 4.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 20,
        },
        [21] = {
            name = 'witte_wijn',
            price = 4.40,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 21,
        },
        [22] = {
            name = 'cava',
            price = 6.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 22,
        },
        [23] = {
            name = 'mojito',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 23,
        },
        [24] = {
            name = 'twerks_candy',
            price = 0.60,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 24,
        },
        [25] = {
            name = 'snikkel_candy',
            price = 0.60,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 25,
        },
        [26] = {
            name = 'chips',
            price = 0.90,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 26,
        },
        [27] = {
            name = 'sandwich',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 27,
        },

    },
    ["cafe"] = {
        [1] = {
            name = 'stella',
            price = 2.50,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'jupiler',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'duvel',
            price = 3.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'maes',
            price = 2.20,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'carapils',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'fanta',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'sprite',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
        [10] = {
            name = 'redbull',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 10,
        },
        [11] = {
            name = 'wine',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 11,
        },
        [12] = {
            name = 'vodka',
            price = 9.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 12,
        },
        [13] = {
            name = 'vodka_redbull',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 13,
        },
        [14] = {
            name = 'whiskey',
            price = 9.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 14,
        },
        [15] = {
            name = 'chips',
            price = 0.90,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 15,
        },
        [16] = {
            name = 'tosti',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 16,
        },
        [17] = {
            name = 'twerks_candy',
            price = 0.60,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 17,
        },
        [18] = {
            name = 'snikkel_candy',
            price = 0.60,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 18,
        },
        [19] = {
            name = 'sandwich',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 19,
        },
        [20] = {
            name = 'desperados',
            price = 5.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 20,
        },
        [21] = {
            name = 'corona',
            price = 5.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 21,
        },

    },
    ["mcdo"] = {
        [1] = {
            name = 'fries',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'hamburger',
            price = 1.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'nuggets',
            price = 7.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'milkshake',
            price = 2.7,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'icecream',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'donut',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
        [10] = {
            name = 'fanta',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 10,
        },
        [11] = {
            name = 'sprite',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 11,
        },
        [12] = {
            name = 'grapejuice',
            price = 6.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 12,
        },

    },
    ["popsdiner"] = {
        [1] = {
            name = 'chickenbucket',
            price = 9.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'nuggets',
            price = 7.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'fries',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'milkshake',
            price = 2.7,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'icecream',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'donut',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
    },
    ["huntingshop"] = {
        [1] = {
            name = 'huntingknife',
            price = 500.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'huntingbait',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'weapon_musket',
            price = 1500,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'shotgun_ammo',
            price = 200.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
    },
    ["taco"] = {
        [1] = {
            name = 'taco',
            price = 3.50,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fries',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'fanta',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'sprite',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'redbull',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },

    },
    ["foodtruck1"] = {
        [1] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fries',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'hotdog',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'pizza_mozzerella',
            price = 7.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
    },
    ["foodtruck2"] = {
        [1] = {
            name = 'cookie',
            price = 1.20,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'muffin',
            price = 1.20,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'icecream',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'milkshake',
            price = 2.7,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'donut',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'pancake',
            price = 5.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 9,
        },
    },
    ["foodtruck3"] = {
        [1] = {
            name = 'eggsbacon',
            price = 8,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'panini_boulet',
            price = 4.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [2] = {
            name = 'panini_chicken_peper',
            price = 4.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [2] = {
            name = 'panini_mozzarella',
            price = 4.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'taco',
            price = 3.5,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'hotdog',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'tosti',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
    },
    ["foodtruck4"] = {
        [1] = {
            name = 'twerks_candy',
            price = 0.60,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'snikkel_candy',
            price = 0.60,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'sandwich',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'rolling_paper',
            price = 1.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'lighter',
            price = 20.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 7,
        },
    },
    ["hotdogstand"] = {
        [1] = {
            name = 'hotdog',
            price = 1.50,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
    },
    ["hamburgerstand"] = {
        [1] = {
            name = 'hotdog',
            price = 1.50,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'kurkakola',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'water_bottle',
            price = 2.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'coffee',
            price = 2.50,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
    },
    ["applestore"] = {
        [1] = {
            name = 'phone',
            price = 850,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'tablet',
            price = 1200,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'laptop',
            price = 2000,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
    },
    ["apotheek"] = {
        [1] = {
            name = 'bandage',
            price = 500.00,
            amount = 500,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'painkillers',
            price = 600,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'hydrochloricacid',
            price = 10.00,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 3,
        },
    },
    ["catsnack"] = {
        [1] = {
            name = "milkshake",
            price = 2.7,
            amount = 25,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "donut",
            price = 1.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cookie",
            price = 1.20,
            amount = 25,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "water_bottle",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "coffee",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "cake",
            price = 4.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "pie",
            price = 1.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "fanta",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "krukakola",
            price = 3.99,
            amount = 25,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "milk",
            price = 1.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 10,
        },
    },
    ["snackbar"] = {
        [1] = {
            name = "tosti",
            price = 20.00,
            amount = 15,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "hotdog",
            price = 1.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "hamburger",
            price = 1.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 4,
        },
        [4] = {
            name = "fries",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 5,
        },
        [5] = {
            name = "pizza_salami",
            price = 7.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 3,
        },
        [6] = {
            name = "pasta_bolognese",
            price = 6,
            amount = 25,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "pasta_carbonara",
            price = 6.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 5,
        },
        [8] = {
            name = "tiramisu",
            price = 3.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 7,
        },
        [9] = {
            name = "chocomousse",
            price = 3.5,
            amount = 25,
            info = {},
            type = "item",
            slot = 12,
        },
        [10] = {
            name = "kurkakola",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 7,
        },
        [11] = {
            name = "fanta",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 8,
        },
        [12] = {
            name = "sprite",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 9,
        },
        [13] = {
            name = "stella",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 10,
        },
        [14] = {
            name = "jupiler",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 11,
        },
        [15] = {
            name = "maes",
            price = 2.20,
            amount = 25,
            info = {},
            type = "item",
            slot = 12,
        },
        [16] = {
            name = "carapils",
            price = 1.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 13,
        },
        [17] = {
            name = "redbull",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 14,
        },
        [18] = {
            name = "duvel",
            price = 3.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 15,
        },
        [19] = {
            name = "vodka_redbull",
            price = 10.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 16,
        },
        [20] = {
            name = "wine",
            price = 3.,
            amount = 25,
            info = {},
            type = "item",
            slot = 17,
        },
        [21] = {
            name = "water_bottle",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 18,
        },
        [22] = {
            name = "coffee'",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 19,
        },
        [23] = {
            name = "mint_tea",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 20,
        },
        [24] = {
            name = "green_tea",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 21,
        },
        [25] = {
            name = "whiskey",
            price = 9.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 22,
        },
    },

    ["pizzeria"] = {
        [1] = {
            name = "pizza_mozzerella",
            price = 7.00,
            amount = 15,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "pizza_salami",
            price = 7.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "pizza_hawai",
            price = 7.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "pizza_vegi",
            price = 7.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "pasta_carbonara",
            price = 6.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "pasta_bolognese",
            price = 6,
            amount = 25,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "tiramisu",
            price = 3.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "fanta",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "sprite",
            price = 20.00,
            amount = 25,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "beer",
            price = 2.50,
            amount = 25,
        },
        [11] = {
            name = "chocomousse",
            price = 3.5,
            amount = 25,
            info = {},
            type = "item",
            slot = 12,
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1.00,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = "icecream",
            price = 1.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 11,
        },
        [3] = {
            name = "chocomousse",
            price = 3.5,
            amount = 25,
            info = {},
            type = "item",
            slot = 12,
        },
        [4] = {
            name = "coffee",
            price = 2.50,
            amount = 25,
            info = {},
            type = "item",
            slot = 13,
        },
    },
}

Config.Locations = {
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(24.47, -1346.62, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(549.13, 2670.85, 42.16, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2556.66, 380.84, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(372.66, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["ltdgasoline5"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0
    },

    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0
    },

    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0
    },

    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(809.68, -2159.13, 29.62, 1.43),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(23.0, -1105.67, 29.8, 162.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation11"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },

    -- -- Casino Locations
    -- ["casino"] = {
    --     ["label"] = "Diamond Casino",
    --     ["coords"] = vector4(949.29, 32.13, 71.95, 79.54),
    --     ["ped"] = 'csb_tomcasino',
    --     ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-coins",
    --     ["targetLabel"] = "Buy Chips",
    --     ["products"] = Config.Products["casino"],
    --     ["showblip"] = true,
    --     ["blipsprite"] = 617,
    --     ["blipcolor"] = 0
    -- },

    ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(937.45, 27.22, 71.83, 61.21),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["bar"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Weedshop Locations
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1171.31, -1570.89, 4.66, 130.03),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipcolor"] = 0
    },

    -- Sea Word Locations
    ["seaword"] = {
        ["label"] = "Sea Word",
        ["coords"] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish",
        ["targetLabel"] = "Sea Word",
        ["products"] = Config.Products["gearshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Leisure Shop Locations
    ["leisureshop"] = {
        ["label"] = "Leisure Shop",
        ["coords"] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Custom stuff starts here

    ["blubblub"] = {
        ["label"] = "Blublub Shop",
        ["coords"] = vector4(-1211.79, -1460.62, 4.3477, 35.47),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = true,
        ["blipsprite"] = 729,
        ["blipcolor"] = 0
    },

    ["fishing"] = {
        ["label"] = "Fishing",
        ["coords"] = vector4(1301.402, 4319.427, 38.202, 310.4),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Fishing Shop",
        ["products"] = Config.Products["fishing"],
        ["showblip"] = true,
        ["blipsprite"] = 754,
        ["blipcolor"] = 0
    },

    ["popeyes"] = {
        ["label"] = "Popeyes",
        ["coords"] = vector4(175.3519, -1447.05, 29.130, 48.18),
        ["ped"] = 's_m_m_strvend_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Fishing Shop",
        ["products"] = Config.Products["kfc"],
        ["showblip"] = true,
        ["blipsprite"] = 436,
        ["blipcolor"] = 0
    },

    ["tequilala"] = {
        ["label"] = "Tequi-la-la",
        ["coords"] = vector4(-561.742, 286.9348, 82.176, 259.0),
        ["ped"] = 'ig_ashley',
        ["scenario"] = "WORLD_HUMAN_DRINKING",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["bar"],
        ["showblip"] = true,
        ["blipsprite"] = 436,
        ["blipcolor"] = 0
    },

    ["nachtwinkel"] = {
        ["label"] = "Liquor Ace",
        ["coords"] = vector4(1392.407, 3606.259, 34.980, 201.1),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["24/7shop"],
        ["showblip"] = true,
        ["blipsprite"] = 430,
        ["blipcolor"] = 0
    },

    ["groveshop"] = {
        ["label"] = "Grove Shop",
        ["coords"] = vector4(-5.55662, -1821.76, 25.319, 150.2),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["jachtwinkel"] = {
        ["label"] = "Bayview Lodge Shop",
        ["coords"] = vector3(-674.994, 5836.406, 17.340),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["huntingshop"],
        ["showblip"] = true,
        ["blipsprite"] = 141,
        ["blipcolor"] = 0
    },

    ["mcdo"] = {
        ["label"] = "McDonalds",
        ["coords"] = vector3(-401.569, 6070.488, 31.500),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["mcdo"],
        ["showblip"] = true,
        ["blipsprite"] = 78,
        ["blipcolor"] = 0
    },

    ["burgershot"] = {
        ["label"] = "Burgershot",
        ["coords"] = vector3(-1193.99, -892.735, 13.995),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["mcdo"],
        ["showblip"] = true,
        ["blipsprite"] = 106,
        ["blipcolor"] = 0
    },

    ["mojito"] = {
        ["label"] = "Place 2 be",
        ["coords"] =vector4(-117.677, 6384.950, 32.180, 108.6),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["bar"],
        ["showblip"] = true,
        ["blipsprite"] = 93,
        ["blipcolor"] = 0
    },

    ["lostmcbar"] = {
        ["label"] = "Hell",
        ["coords"] = vector4(-21.1129, 6480.945, 31.493, 145.1),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["cafe"],
        ["showblip"] = true,
        ["blipsprite"] = 93,
        ["blipcolor"] = 0
    },

    ["tacoshop"] = {
        ["label"] = "The Taco Farmer",
        ["coords"] = vector4(10.18538, -1604.18, 29.371, 217.8),
        ["ped"] = 'u_f_o_eileen',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["taco"],
        ["showblip"] = true,
        ["blipsprite"] = 93,
        ["blipcolor"] = 0
    },

    ["GABZ-VANILLAUNICORN"] = {
        ["label"] = "Vanilla Unicorn Stripclub",
        ["coords"] = vector4(129.2591, -1283.67, 29.269, 115.2),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["bar"],
        ["showblip"] = true,
        ["blipsprite"] = 279,
        ["blipcolor"] = 0
    },

    ["applestore"] = {
        ["label"] = "Apple Store",
        ["coords"] = vector4(148.9965, -234.633, 54.424, 341.8),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["applestore"],
        ["showblip"] = true,
        ["blipsprite"] = 279,
        ["blipcolor"] = 0
    },

    ["apotheek"] = {
        ["label"] = "Apotheek Prik",
        ["coords"] = vector3(376.5866, -829.494, 29.291),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["apotheek"],
        ["showblip"] = true,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["zuipschuit"] = {
        ["label"] = "De Zuipschuit",
        ["coords"] = vector4(122.2702, -1038.61, 29.277, 73.01),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["snackbar"],
        ["showblip"] = true,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hetblokje"] = {
        ["label"] = "Het Blokje",
        ["coords"] = vector4(188.5457, -919.197, 31.434, 329.3),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["foodtruck1"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["kremglaze1"] = {
        ["label"] = "Krem Glaze",
        ["coords"] = vector4(228.3388, -907.315, 31.119, 64.42),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["foodtruck2"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["kremglaze2"] = {
        ["label"] = "Krem Glaze",
        ["coords"] = vector4(222.0675, -915.917, 30.003, 58.14),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["foodtruck2"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["tgazetje1"] = {
        ["label"] = "'t Gazetje",
        ["coords"] = vector4(-1636.68, -1092.20, 12.076, 318.8),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["foodtruck4"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["tgazetje2"] = {
        ["label"] = "'t Gazetje",
        ["coords"] = vector4(-1645.19, -1102.21, 12.551, 317.7),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["foodtruck4"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["pizzeria"] = {
        ["label"] = "Pizzeria Luchetti's",
        ["coords"] = vector4(288.9403, -977.982, 29.433, 2.562),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["pizzeria"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hotdogstand1"] = {
        ["label"] = "Hetenond",
        ["coords"] = vector4(-1683.44, -1124.33, 13.152, 116.6),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["hotdogstand"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hotdogstand2"] = {
        ["label"] = "Hetenond",
        ["coords"] = vector4(-1835.30, -1233.91, 13.017, 39.37),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["hotdogstand"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hotdogstand3"] = {
        ["label"] = "Hetenond",
        ["coords"] = vector4(1947.682, 3848.505, 32.176, 341.4),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["hotdogstand"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hotdogstand4"] = {
        ["label"] = "Hetenond",
        ["coords"] = vector4(-1720.33, -1104.13, 13.017, 37.53),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["hotdogstand"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hotdogstand5"] = {
        ["label"] = "Hetenond",
        ["coords"] = vector4(-1638.07, -1083.27, 13.075, 239.6),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["hotdogstand"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["cafesandy1"] = {
        ["label"] = "Hapje Tapje",
        ["coords"] = vector4(1983.278, 3053.771, 47.215, 235.9),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["cafe"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },

    ["hamburgerstand1"] = {
        ["label"] = "Vettig & Prettig",
        ["coords"] = vector3(-1695.06, -1071.73, 13.041),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["hamburgerstand"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipcolor"] = 0
    },


}